name: Update README with Recent Activity

on:
  schedule:
    - cron: "*/30 * * * *"  # Updates every 30 minutes
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readme-typing-effect
